package Paneles;

import Modelos.ObraSocial;


public class modificarObra extends javax.swing.JPanel {

    panelModificacion pModif;
    boolean ob1,ob2,ob3;
    public modificarObra(panelModificacion p) {
        initComponents();
        pModif = p;
        ob1 = false;
        ob2 = false;
        ob3 = false;
        int cant = verificarCantOb();
        if(cant == 0)
        {    
            buttonModificarOb.setVisible(false);
            labelOB1.setVisible(false);
            labelOB2.setVisible(false);
            labelOB3.setVisible(false);
            comboboxOB1.setVisible(false);
            comboboxOb2.setVisible(false);
            comboboxOb3.setVisible(false);
            checkbox1.setVisible(false);
            checkbox2.setVisible(false);
            checkbox3.setVisible(false);
        }else{
            if(cant == 1)
            {
            noTieneObraSocial.setVisible(false);
            traerObraSocial(cant);
            labelOB2.setVisible(false);
            labelOB3.setVisible(false);
            comboboxOb2.setVisible(false);
            comboboxOb3.setVisible(false);
            checkbox2.setVisible(false);
            checkbox3.setVisible(false);

            }else{
                if(cant == 2)
                {
                    noTieneObraSocial.setVisible(false);
                    traerObraSocial(cant);
                    labelOB3.setVisible(false);
                    comboboxOb3.setVisible(false);
                    checkbox3.setVisible(false);
                }else{
                    noTieneObraSocial.setVisible(false);
                    
                    traerObraSocial(cant);
                }
            }
        }
        ApagarComboBox();
    }
    
    public void ApagarComboBox()
   {
       comboboxOB1.setEnabled(false);
       comboboxOb2.setEnabled(false);
       comboboxOb3.setEnabled(false);
   }
    private void traerObraSocial(int cant) {
        ObraSocial ob = new ObraSocial();
        ObraSocial[] obs = new ObraSocial[cant];
        obs = ob.traerObrasDeUnCliente(pModif.traerDni(),cant);
        if(cant == 1)
        {
            labelOB1.setText(obs[cant-1].getNombre());
            ob = ob.CargarPlanes(obs[cant-1].getNombre());
            cargarPlanes(ob,1);
        }else{
            if(cant == 2)
            {
                labelOB1.setText(obs[cant-1].getNombre());
                ob = ob.CargarPlanes(obs[cant-1].getNombre());
                cargarPlanes(ob,1);
                labelOB2.setText(obs[cant-2].getNombre());
                ob = ob.CargarPlanes(obs[cant-2].getNombre());
                cargarPlanes(ob,2);
            }else{
                labelOB1.setText(obs[cant-1].getNombre());
                ob = ob.CargarPlanes(obs[cant-1].getNombre());
                cargarPlanes(ob,1);
                labelOB2.setText(obs[cant-2].getNombre());
                ob = ob.CargarPlanes(obs[cant-2].getNombre());
                cargarPlanes(ob,2);
                labelOB3.setText(obs[cant-3].getNombre());
                ob = ob.CargarPlanes(obs[cant-3].getNombre());
                cargarPlanes(ob,3);
            }
    }
    }
    
    
    private int verificarCantOb() {
        ObraSocial oManager = new ObraSocial();
        String dni = pModif.traerDni();
        int cant = oManager.ObtenerCantobDeUnCliente(dni);
        return cant;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOB2 = new org.jdesktop.swingx.table.LabelProperties();
        labelOB3 = new org.jdesktop.swingx.table.LabelProperties();
        labelOB1 = new org.jdesktop.swingx.table.LabelProperties();
        comboboxOb2 = new org.edisoncor.gui.comboBox.ComboBoxRect();
        comboboxOB1 = new org.edisoncor.gui.comboBox.ComboBoxRect();
        comboboxOb3 = new org.edisoncor.gui.comboBox.ComboBoxRect();
        buttonModificarOb = new org.edisoncor.gui.button.ButtonAeroRound();
        checkbox1 = new javax.swing.JCheckBox();
        checkbox2 = new javax.swing.JCheckBox();
        checkbox3 = new javax.swing.JCheckBox();
        noTieneObraSocial = new javax.swing.JLabel();

        setOpaque(false);

        labelOB2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 2, true));
        labelOB2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N

        labelOB3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 2, true));
        labelOB3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N

        labelOB1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 2, true));
        labelOB1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N

        buttonModificarOb.setBackground(new java.awt.Color(0, 102, 102));
        buttonModificarOb.setText("Modificar Obras");
        buttonModificarOb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarObActionPerformed(evt);
            }
        });

        checkbox1.setOpaque(false);
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });

        checkbox2.setOpaque(false);
        checkbox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox2ItemStateChanged(evt);
            }
        });

        checkbox3.setOpaque(false);
        checkbox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox3ItemStateChanged(evt);
            }
        });

        noTieneObraSocial.setText("Dicho cliente no tiene obras sociales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelOB1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(labelOB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelOB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboboxOb3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkbox3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboboxOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkbox1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboboxOb2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkbox2))
                            .addComponent(buttonModificarOb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(noTieneObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(noTieneObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox1)
                    .addComponent(comboboxOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboboxOb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelOB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkbox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelOB3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboboxOb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkbox3))
                .addGap(26, 26, 26)
                .addComponent(buttonModificarOb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModificarObActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarObActionPerformed
        String[] obs = new String[3];
        String[] pObs = new String[3];
        if(ob1 = checkbox1.isSelected())
        {
            Object ob1 = comboboxOB1.getSelectedItem();
            String planNuevo = String.valueOf(ob1);
            String nombreob = labelOB1.getText();
            obs[0] = nombreob;
            pObs[0] = planNuevo;    
        }else{
            obs[0] = null;
            pObs[0] = null; 
        }
        if(ob2 = checkbox2.isSelected())
        {
            Object ob1 = comboboxOb2.getSelectedItem();
            String planNuevo = String.valueOf(ob1);
            String nombreob = labelOB2.getText();
            obs[1] = nombreob;
            pObs[1] = planNuevo;    
        }else{
            obs[1] = null;
            pObs[1] = null; 
        }
        if(ob3 = checkbox3.isSelected())
        {
            Object ob1 = comboboxOb3.getSelectedItem();
            String planNuevo = String.valueOf(ob1);
            String nombreob = labelOB3.getText();
            obs[2] = nombreob;
            pObs[2] = planNuevo;    
        }else{
            obs[2] = null;
            pObs[2] = null; 
        }
        ObraSocial ob = new ObraSocial();
        ob.ModificarCobertura(pModif.traerDni(),obs,pObs);

    }//GEN-LAST:event_buttonModificarObActionPerformed

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        if(ob1 = checkbox1.isSelected()){
            comboboxOB1.setEnabled(true);
        }else{
             comboboxOB1.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void checkbox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox2ItemStateChanged
        if(ob1 = checkbox2.isSelected()){
            comboboxOb2.setEnabled(true);
        }else{
             comboboxOb2.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox2ItemStateChanged

    private void checkbox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox3ItemStateChanged
        if(ob1 = checkbox3.isSelected()){
            comboboxOb3.setEnabled(true);
        }else{
             comboboxOb3.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox3ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAeroRound buttonModificarOb;
    private javax.swing.JCheckBox checkbox1;
    private javax.swing.JCheckBox checkbox2;
    private javax.swing.JCheckBox checkbox3;
    private org.edisoncor.gui.comboBox.ComboBoxRect comboboxOB1;
    private org.edisoncor.gui.comboBox.ComboBoxRect comboboxOb2;
    private org.edisoncor.gui.comboBox.ComboBoxRect comboboxOb3;
    private org.jdesktop.swingx.table.LabelProperties labelOB1;
    private org.jdesktop.swingx.table.LabelProperties labelOB2;
    private org.jdesktop.swingx.table.LabelProperties labelOB3;
    private javax.swing.JLabel noTieneObraSocial;
    // End of variables declaration//GEN-END:variables

    private void cargarPlanes(ObraSocial ob,int cant) {
         int i = 0;
         String[] planes = ob.getPlan();
         int tam = planes.length; 
        if(cant == 1)
         {
            comboboxOB1.removeAllItems();
            while(tam > 0)
            {
                comboboxOB1.addItem(planes[i]);
                tam--;
                i++;
            }
         }else{
             if(cant == 2)
             {
                comboboxOb2.removeAllItems();
                 while(tam > 0)
                {
                    comboboxOb2.addItem(planes[i]);
                    tam--;
                    i++;
                }
             }else{
                 comboboxOb3.removeAllItems();
                 while(tam > 0)
                {
                    comboboxOb3.addItem(planes[i]);
                    tam--;
                    i++;
                }
             }
         }
         
    }
}
