/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Modelos.ObraSocial;


public class nuevaObra extends javax.swing.JPanel {

    panelModificacion pModif;
    public nuevaObra(panelModificacion p) {
        initComponents();
        pModif = p;
        obLlenas.setVisible(false);
        CargarObraSocial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboOB1 = new org.edisoncor.gui.comboBox.ComboBoxRect();
        labelPlan = new org.edisoncor.gui.label.LabelCustom();
        labelNombre = new org.edisoncor.gui.label.LabelCustom();
        comboPlanOB1 = new org.edisoncor.gui.comboBox.ComboBoxRect();
        buttonAgregarOb = new org.edisoncor.gui.button.ButtonAeroRound();
        obLlenas = new javax.swing.JLabel();

        setOpaque(false);

        ComboOB1.setColorDeBorde(new java.awt.Color(0, 153, 0));
        ComboOB1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ComboOB1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboOB1FocusLost(evt);
            }
        });

        labelPlan.setBackground(new java.awt.Color(0, 204, 0));
        labelPlan.setText("Plan");
        labelPlan.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        labelNombre.setBackground(new java.awt.Color(0, 204, 0));
        labelNombre.setText("nombre");
        labelNombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        comboPlanOB1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N

        buttonAgregarOb.setBackground(new java.awt.Color(0, 102, 102));
        buttonAgregarOb.setText("Agregar obra social");
        buttonAgregarOb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarObActionPerformed(evt);
            }
        });

        obLlenas.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        obLlenas.setText("El cliente ya posee todas las obras que se manejan en el sistema.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obLlenas)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAgregarOb, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComboOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboPlanOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(obLlenas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPlanOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAgregarOb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void CargarObraSocial()
  {
      ObraSocial[] obs = new ObraSocial[3];
      ObraSocial ob = new ObraSocial();
      obs = ob.traerObrasQueTiene(pModif.traerDni());
      int cantob = ob.ObtenerCantobDeUnCliente(pModif.traerDni());
      int cantobEnSistema = ob.contarObrasSociales();
      if(cantob != cantobEnSistema)
      {
            if(cantob == 0)
            {
                CargarObrasSociales();
            }else{
                if(obs[0] != null)
                {
                    int oscod = ob.ObtenerCcod(obs[0].getNombre());
                    Cargar(oscod); // cargar obras sociales menos la del oscod  
                }     
            }               
      }else{
          obLlenas.setVisible(true);
          labelNombre.setVisible(false);
          labelPlan.setVisible(false);
          ComboOB1.setVisible(false);
          comboPlanOB1.setVisible(false);
          buttonAgregarOb.setVisible(false);
      }
         
      
      
  }

public void CargarObrasSociales()
  {
      ObraSocial ob = new ObraSocial();
      int cant = ob.contarObrasSociales();
      while(cant > 0)
      {
          ob = ob.Cargar(cant);
          ComboOB1.addItem(ob.getNombre());
          cant--;
      }
      
      
  }
    private void ComboOB1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboOB1FocusLost
        comboPlanOB1.removeAllItems();
        Object ob1 = ComboOB1.getSelectedItem();
        String nombreOb1 = String.valueOf(ob1);
        ObraSocial ob = new ObraSocial();
        ob.Cargar(0);
        ob = ob.CargarPlanes(nombreOb1);
        int i = 0;
        String[] planes;
        planes = ob.getPlan();
        int tam = ob.getPlan().length;
        while(tam > 0)
        {
            comboPlanOB1.addItem(ob.getPlan()[i]);
            tam--;
            i++;
        }
    }//GEN-LAST:event_ComboOB1FocusLost

    private void buttonAgregarObActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarObActionPerformed
        Object ob1 = ComboOB1.getSelectedItem();
        String obs = String.valueOf(ob1);
        Object pob1 = comboPlanOB1.getSelectedItem();
        String pObs = String.valueOf(pob1);     
        String dni = pModif.traerDni();
        ObraSocial ob = new ObraSocial();
        System.out.println(obs);
        ob.AltaCobertura(dni, obs, pObs);
        
    }//GEN-LAST:event_buttonAgregarObActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.comboBox.ComboBoxRect ComboOB1;
    private org.edisoncor.gui.button.ButtonAeroRound buttonAgregarOb;
    private org.edisoncor.gui.comboBox.ComboBoxRect comboPlanOB1;
    private org.edisoncor.gui.label.LabelCustom labelNombre;
    private org.edisoncor.gui.label.LabelCustom labelPlan;
    private javax.swing.JLabel obLlenas;
    // End of variables declaration//GEN-END:variables

    private void Cargar(int oscod) {
        ObraSocial ob = new ObraSocial();
        ob = ob.ObtenerObrasMenosLaOscodDeParametro(oscod);
        ComboOB1.addItem(ob.getNombre());
        int tam = ob.getPlan().length;
        int i= 0;
        while(tam > 0)
        {
            comboPlanOB1.addItem(ob.getPlan()[i]);
            tam--;
            i++;
        }
    }
}
