/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Interfaces.Principal;
import Modelos.Venta;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author glupi
 */
public class panelFormaPago extends javax.swing.JPanel {

    /**
     * Creates new form panelFormaPago
     */
    Venta vta;
    public panelFormaPago(Venta vta) {
        this.vta = vta;
        initComponents();
        
        importeTF.setText(""+vta.getMonto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        labelRound5 = new org.edisoncor.gui.label.LabelRound();
        formaPagoLbl = new org.edisoncor.gui.label.LabelRound();
        labelRound7 = new org.edisoncor.gui.label.LabelRound();
        labelRound8 = new org.edisoncor.gui.label.LabelRound();
        jPanel1 = new javax.swing.JPanel();
        tipoPagoLbl = new org.edisoncor.gui.label.LabelCustom();
        efectivoRB = new javax.swing.JRadioButton();
        tjtaCredRB = new javax.swing.JRadioButton();
        tjtaDebRB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        labelCustom5 = new org.edisoncor.gui.label.LabelCustom();
        importeTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        creditoLbl = new org.edisoncor.gui.label.LabelCustom();
        jPanel4 = new javax.swing.JPanel();
        credVisaRB = new javax.swing.JRadioButton();
        nroTjtCredLbl = new org.edisoncor.gui.label.LabelCustom();
        nrotjtaCredTF = new javax.swing.JTextField();
        codPostalTjtCredLbl = new org.edisoncor.gui.label.LabelCustom();
        codPostTjtaCredTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        credNjaRB = new javax.swing.JRadioButton();
        nbreTitTjtCredLbl = new org.edisoncor.gui.label.LabelCustom();
        titularTjtaCredTF = new javax.swing.JTextField();
        codSegTjtCredLbl = new org.edisoncor.gui.label.LabelCustom();
        codSegTjtaCredTF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        credNvdaRB = new javax.swing.JRadioButton();
        dirTjtCredLbl = new org.edisoncor.gui.label.LabelCustom();
        dirTitularTjtaCredTF = new javax.swing.JTextField();
        debitoLbl = new org.edisoncor.gui.label.LabelCustom();
        jPanel9 = new javax.swing.JPanel();
        debVisaRB = new javax.swing.JRadioButton();
        nroTjtDebLbl = new org.edisoncor.gui.label.LabelCustom();
        nroTjtaDebTF = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        debSderRB = new javax.swing.JRadioButton();
        dniTitTjtDebLbl = new org.edisoncor.gui.label.LabelCustom();
        dniTitularTjtaDebTF = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        debICBCRB = new javax.swing.JRadioButton();
        codSegTjtDebLbl = new org.edisoncor.gui.label.LabelCustom();
        codSegTjtaDebTF = new javax.swing.JTextField();
        cargarFormaPago = new javax.swing.JButton();
        checkob = new javax.swing.JCheckBox();

        setOpaque(false);

        jPanel8.setOpaque(false);

        labelRound5.setBackground(new java.awt.Color(51, 123, 123));
        labelRound5.setText("1. Seleccionar Productos");

        formaPagoLbl.setBackground(new java.awt.Color(0, 204, 51));
        formaPagoLbl.setText("2. Forma de Pago");

        labelRound7.setBackground(new java.awt.Color(51, 123, 123));
        labelRound7.setText("3. Datos Obra Social");
        labelRound7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRound7MouseClicked(evt);
            }
        });

        labelRound8.setBackground(new java.awt.Color(51, 123, 123));
        labelRound8.setText("4. Facturacion");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(labelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(formaPagoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(labelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(labelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .addComponent(formaPagoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelRound8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setOpaque(false);

        tipoPagoLbl.setBackground(new java.awt.Color(0, 204, 0));
        tipoPagoLbl.setText("Tipo de Pago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tipoPagoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tipoPagoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        buttonGroup1.add(efectivoRB);
        efectivoRB.setText("Efectivo");
        efectivoRB.setOpaque(false);
        efectivoRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivoRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(tjtaCredRB);
        tjtaCredRB.setText("Tarjeta de Credito");
        tjtaCredRB.setOpaque(false);
        tjtaCredRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjtaCredRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(tjtaDebRB);
        tjtaDebRB.setText("Tarjeta de Debito");
        tjtaDebRB.setOpaque(false);

        jPanel2.setOpaque(false);

        labelCustom5.setBackground(new java.awt.Color(0, 204, 0));
        labelCustom5.setText("Importe a pagar");

        importeTF.setEditable(false);
        importeTF.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        importeTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(importeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(importeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        creditoLbl.setBackground(new java.awt.Color(0, 204, 0));
        creditoLbl.setText("Tarjeta de Credito");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 1846, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel4.setOpaque(false);

        buttonGroup2.add(credVisaRB);
        credVisaRB.setText("Visa");
        credVisaRB.setOpaque(false);
        credVisaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credVisaRBActionPerformed(evt);
            }
        });

        nroTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
        nroTjtCredLbl.setText("Numero de tarjeta");

        nrotjtaCredTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        codPostalTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
        codPostalTjtCredLbl.setText("Codigo postal");

        codPostTjtaCredTF.setToolTipText("");
        codPostTjtaCredTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(credVisaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nroTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nrotjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(codPostalTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codPostTjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credVisaRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nrotjtaCredTF)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(codPostalTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(codPostTjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(nroTjtCredLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setOpaque(false);

        buttonGroup2.add(credNjaRB);
        credNjaRB.setText("Naranja");
        credNjaRB.setOpaque(false);
        credNjaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credNjaRBActionPerformed(evt);
            }
        });

        nbreTitTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
        nbreTitTjtCredLbl.setText("Nombre de titular");

        titularTjtaCredTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        codSegTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
        codSegTjtCredLbl.setText("Codigo de seguridad");

        codSegTjtaCredTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(credNjaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbreTitTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titularTjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(codSegTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codSegTjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credNjaRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titularTjtaCredTF)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(codSegTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(codSegTjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(nbreTitTjtCredLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setOpaque(false);

        buttonGroup2.add(credNvdaRB);
        credNvdaRB.setText("Nevada");
        credNvdaRB.setOpaque(false);
        credNvdaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credNvdaRBActionPerformed(evt);
            }
        });

        dirTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
        dirTjtCredLbl.setText("Direccion");

        dirTitularTjtaCredTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(credNvdaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dirTjtCredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dirTitularTjtaCredTF, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credNvdaRB, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(dirTitularTjtaCredTF)
            .addComponent(dirTjtCredLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        debitoLbl.setBackground(new java.awt.Color(0, 204, 0));
        debitoLbl.setText("Tarjeta de Debito");

        jPanel9.setOpaque(false);

        buttonGroup3.add(debVisaRB);
        debVisaRB.setText("Visa");
        debVisaRB.setOpaque(false);

        nroTjtDebLbl.setBackground(new java.awt.Color(0, 204, 0));
        nroTjtDebLbl.setText("Numero tarjeta");

        nroTjtaDebTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(debVisaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nroTjtDebLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(nroTjtaDebTF, javax.swing.GroupLayout.PREFERRED_SIZE, 1602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(debVisaRB, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(nroTjtaDebTF, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(nroTjtDebLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setOpaque(false);

        buttonGroup3.add(debSderRB);
        debSderRB.setText("Santander");
        debSderRB.setOpaque(false);
        debSderRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debSderRBActionPerformed(evt);
            }
        });

        dniTitTjtDebLbl.setBackground(new java.awt.Color(0, 204, 0));
        dniTitTjtDebLbl.setText("DNI del titular");

        dniTitularTjtaDebTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        dniTitularTjtaDebTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTitularTjtaDebTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(debSderRB)
                .addGap(7, 7, 7)
                .addComponent(dniTitTjtDebLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(dniTitularTjtaDebTF, javax.swing.GroupLayout.PREFERRED_SIZE, 1601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(debSderRB, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(dniTitularTjtaDebTF, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(dniTitTjtDebLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setOpaque(false);

        buttonGroup3.add(debICBCRB);
        debICBCRB.setText("ICBC");
        debICBCRB.setOpaque(false);
        debICBCRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debICBCRBActionPerformed(evt);
            }
        });

        codSegTjtDebLbl.setBackground(new java.awt.Color(0, 204, 0));
        codSegTjtDebLbl.setText("Codigo de seguridad");

        codSegTjtaDebTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(debICBCRB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codSegTjtDebLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(codSegTjtaDebTF, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(debICBCRB, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(codSegTjtaDebTF, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(codSegTjtDebLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cargarFormaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CompletarVta 48px.png"))); // NOI18N
        cargarFormaPago.setText("Completar");
        cargarFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFormaPagoActionPerformed(evt);
            }
        });

        checkob.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        checkob.setText("Obra Social");
        checkob.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(efectivoRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tjtaDebRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tjtaCredRB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(341, 341, 341))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(341, 341, 341))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(debitoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(checkob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cargarFormaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(363, 363, 363))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(efectivoRB)
                .addGap(20, 20, 20)
                .addComponent(tjtaCredRB)
                .addGap(20, 20, 20)
                .addComponent(tjtaDebRB)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(debitoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(checkob, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarFormaPago)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void efectivoRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivoRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectivoRBActionPerformed

    private void credVisaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credVisaRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credVisaRBActionPerformed

    private void credNjaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credNjaRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credNjaRBActionPerformed

    private void credNvdaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credNvdaRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credNvdaRBActionPerformed

    private void dniTitularTjtaDebTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTitularTjtaDebTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTitularTjtaDebTFActionPerformed

    private void debSderRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debSderRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debSderRBActionPerformed

    private void debICBCRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debICBCRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debICBCRBActionPerformed

    private void tjtaCredRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjtaCredRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjtaCredRBActionPerformed

    private void labelRound7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRound7MouseClicked
        
    }//GEN-LAST:event_labelRound7MouseClicked

    private void cargarFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFormaPagoActionPerformed
         if(efectivoRB.isSelected()||tjtaCredRB.isSelected()||tjtaDebRB.isSelected()){
            formaPagoLbl.setBackground(new java.awt.Color(0, 204, 0));
            tipoPagoLbl.setBackground(new java.awt.Color(0, 204, 0));
            if(efectivoRB.isSelected()){
                vta.setFormaDePago("EFECTIVO");
                vta.setDescuento(15);
                if(checkob.isSelected())
                {
                    PasarAObraSocial();
                }else{
                    pasarAFacturacion();
                }
                
            }
            
            if(tjtaCredRB.isSelected()){
                if(credVisaRB.isSelected()||credNjaRB.isSelected()||credNvdaRB.isSelected()){
                    vta.setFormaDePago("TARJETA DE CREDITO");
                    vta.setNroTjtaCred(nrotjtaCredTF.getText());
                    vta.setNbreTitularCred(titularTjtaCredTF.getText());
                    vta.setCgoPostalCred(codPostTjtaCredTF.getText());
                    vta.setCgoSeguridadCred(codSegTjtaCredTF.getText());
                    vta.setDireccionCred(dirTitularTjtaCredTF.getText());
                    if(vta.getDireccionCred().equals("")||vta.getNroTjtaCred().equals("")||vta.getCgoPostalCred().equals("")||vta.getNbreTitularCred().equals("")||vta.getCgoSeguridadCred().equals("")){
                        JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Campos vacios", JOptionPane.ERROR_MESSAGE);
                        if(vta.getNroTjtaCred().equals(""))
                            nroTjtCredLbl.setBackground(Color.red);
                        else
                            nroTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
                        if(vta.getNbreTitularCred().equals(""))
                            nbreTitTjtCredLbl.setBackground(Color.red);
                        else
                            nbreTitTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
                        if(vta.getDireccionCred().equals(""))
                            dirTjtCredLbl.setBackground(Color.red);
                        else
                            dirTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
                        if(vta.getCgoPostalCred().equals(""))
                            codPostalTjtCredLbl.setBackground(Color.red);
                        else 
                            codPostalTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
                        if(vta.getCgoSeguridadCred().equals(""))
                            codSegTjtCredLbl.setBackground(Color.red);
                        else
                            codSegTjtCredLbl.setBackground(new java.awt.Color(0, 204, 0));
                    }else{
                        if(credVisaRB.isSelected()){
                            vta.setTarjetaCredito("VISA");
                        }
                        if(credNjaRB.isSelected()){
                            vta.setTarjetaCredito("NARANJA");
                        }
                        if(credNvdaRB.isSelected()){
                            vta.setTarjetaCredito("NEVADA");
                        }
                        PasarAObraSocial();
                    }
                }else{
                    creditoLbl.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Debe seleccionar una tarjeta para continuar", "Ninguna tarjeta valida", JOptionPane.ERROR_MESSAGE);
                }
            }
            if(tjtaDebRB.isSelected()){
                if(debVisaRB.isSelected()||debSderRB.isSelected()||debICBCRB.isSelected()){
                    vta.setDniTitularDeb(dniTitularTjtaDebTF.getText());
                    vta.setNroTarjetaDeb(nroTjtaDebTF.getText());
                    vta.setCgoSeguridadDeb(codSegTjtaDebTF.getText());
                    if(vta.getDniTitularDeb().equals("")||vta.getNroTarjetaDeb().equals("")||vta.getCgoSeguridadDeb().equals("")){
                        JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Campos vacios", JOptionPane.ERROR_MESSAGE);
                        if(vta.getDniTitularDeb().equals(""))
                            dniTitTjtDebLbl.setBackground(Color.red);
                        else
                            dniTitTjtDebLbl.setBackground(new java.awt.Color(0, 204, 0));
                        if(vta.getNroTarjetaDeb().equals(""))
                            nroTjtDebLbl.setBackground(Color.red);
                        else
                            nroTjtDebLbl.setBackground(new java.awt.Color(0, 204, 0));
                        if(vta.getCgoSeguridadDeb().equals(""))
                            codSegTjtDebLbl.setBackground(Color.red);
                        else
                            codSegTjtDebLbl.setBackground(new java.awt.Color(0, 204, 0));
                        
                    }else{
                        if(debVisaRB.isSelected()){
                        vta.setTarjetaDebito("VISA");
                        }
                        if(debSderRB.isSelected()){
                            vta.setTarjetaDebito("SANTANDER");
                        }
                        if(debICBCRB.isSelected()){
                            vta.setTarjetaDebito("ICBC");
                        }
                        PasarAObraSocial();
                    }
                }else{
                    debitoLbl.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Debe seleccionar una tarjeta para continuar", "Ninguna tarjeta valida", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            formaPagoLbl.setBackground(Color.red);
            tipoPagoLbl.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe seleccionar una forma de pago para continuar", "Ninguna forma de pago valida", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_cargarFormaPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cargarFormaPago;
    private javax.swing.JCheckBox checkob;
    private javax.swing.JTextField codPostTjtaCredTF;
    private org.edisoncor.gui.label.LabelCustom codPostalTjtCredLbl;
    private org.edisoncor.gui.label.LabelCustom codSegTjtCredLbl;
    private org.edisoncor.gui.label.LabelCustom codSegTjtDebLbl;
    private javax.swing.JTextField codSegTjtaCredTF;
    private javax.swing.JTextField codSegTjtaDebTF;
    private javax.swing.JRadioButton credNjaRB;
    private javax.swing.JRadioButton credNvdaRB;
    private javax.swing.JRadioButton credVisaRB;
    private org.edisoncor.gui.label.LabelCustom creditoLbl;
    private javax.swing.JRadioButton debICBCRB;
    private javax.swing.JRadioButton debSderRB;
    private javax.swing.JRadioButton debVisaRB;
    private org.edisoncor.gui.label.LabelCustom debitoLbl;
    private javax.swing.JTextField dirTitularTjtaCredTF;
    private org.edisoncor.gui.label.LabelCustom dirTjtCredLbl;
    private org.edisoncor.gui.label.LabelCustom dniTitTjtDebLbl;
    private javax.swing.JTextField dniTitularTjtaDebTF;
    private javax.swing.JRadioButton efectivoRB;
    private org.edisoncor.gui.label.LabelRound formaPagoLbl;
    private javax.swing.JTextField importeTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.edisoncor.gui.label.LabelCustom labelCustom5;
    private org.edisoncor.gui.label.LabelRound labelRound5;
    private org.edisoncor.gui.label.LabelRound labelRound7;
    private org.edisoncor.gui.label.LabelRound labelRound8;
    private org.edisoncor.gui.label.LabelCustom nbreTitTjtCredLbl;
    private org.edisoncor.gui.label.LabelCustom nroTjtCredLbl;
    private org.edisoncor.gui.label.LabelCustom nroTjtDebLbl;
    private javax.swing.JTextField nroTjtaDebTF;
    private javax.swing.JTextField nrotjtaCredTF;
    private org.edisoncor.gui.label.LabelCustom tipoPagoLbl;
    private javax.swing.JTextField titularTjtaCredTF;
    private javax.swing.JRadioButton tjtaCredRB;
    private javax.swing.JRadioButton tjtaDebRB;
    // End of variables declaration//GEN-END:variables

    private void PasarAObraSocial() {
        panelObraSocial pObraSocial = new panelObraSocial(vta);
        pObraSocial.setSize(2239, 1309);
        pObraSocial.setLocation(0,0);
        this.removeAll();
        this.add(pObraSocial);
        this.revalidate();
        this.repaint();
    }

    private void pasarAFacturacion() {
        System.out.println(vta.getMedicamentos().get(0).getNombre());
        panelFacturacion pFacturacion = new panelFacturacion(vta);
        pFacturacion.setSize(2239, 1309);
        pFacturacion.setLocation(0,0);
        this.removeAll();
        this.add(pFacturacion);
        this.revalidate();
        this.repaint();
    }
}
